const { google } = require("googleapis");
const fs = require("fs");
const path = require("path");

function loadEnvLocal() {
    const envPath = path.join(process.cwd(), ".env.local");
    const content = fs.readFileSync(envPath, "utf8");
    const env = {};
    content.split("\n").forEach(line => {
        const [key, ...val] = line.split("=");
        if (key && val.length) {
            env[key.trim()] = val.join("=").trim().replace(/"/g, "");
        }
    });
    return env;
}

// Very basic transliteration/slugification for Hebrew to English keys
function slugify(text) {
    if (!text) return "row";
    
    // Some manual common mappings to have decent English keys
    const map = {
        "מחיר קנייה": "purchase_price",
        "משקל יחידה": "unit_weight",
        "כמות": "quantity",
        "מכס": "customs",
        "חליפין": "exchange_rate",
        "שילוח": "shipping",
        "שחרור": "clearance",
        "עמלה": "commission",
        "מס": "tax",
        "מינימום": "min",
        "מומלץ": "recommended",
        "יעד": "target",
        "נקי": "net_profit"
    };

    let slug = text;
    for (const [heb, eng] of Object.entries(map)) {
        if (text.includes(heb)) {
            slug = eng;
            break; // take first match for simplicity
        }
    }
    
    if (slug === text) {
        // If no match, just clean it up slightly and prefix with 'field'
        slug = "field";
    }

    return slug;
}

async function main() {
  const env = loadEnvLocal();
  const email = env.GOOGLE_SERVICE_ACCOUNT_EMAIL;
  const rawKey = env.GOOGLE_PRIVATE_KEY?.replace(/\\n/g, '\n');
  const spreadsheetId = env.SPREADSHEET_ID;

  if (!email || !rawKey || !spreadsheetId) {
    console.error("Missing Google Sheets credentials in .env.local");
    return;
  }

  const jwt = new google.auth.JWT(
    email,
    undefined,
    rawKey,
    ["https://www.googleapis.com/auth/spreadsheets.readonly"]
  );

  const sheets = google.sheets({ version: "v4", auth: jwt });

  try {
    const spreadRes = await sheets.spreadsheets.get({ spreadsheetId });
    const titles = spreadRes.data.sheets.map(s => s.properties.title);
    const mainSheet = titles.includes("Main") ? "Main" : (titles.includes("Price Calculator") ? "Price Calculator" : titles[0]);

    const mainRes = await sheets.spreadsheets.values.get({
      spreadsheetId,
      range: `${mainSheet}!A1:D150`
    });
    
    if (mainRes.data.values) {
        const fields = mainRes.data.values.map((row, i) => {
            const rowIndex = i + 1;
            const label = row[0] || "";
            if (!label || label === "Title" || label === "Label") return null;
            
            const slug = slugify(label);
            const id = `${slug}_${rowIndex}`; // Ensure uniqueness
            
            return {
                id,
                rowIndex,
                label,
                description: row[2] || "",
                hint: row[3] || ""
            };
        }).filter(Boolean);
        
        // Let's generate lib/excel-map.ts
        let fileContent = `/**\n * Source of Truth: Mapping of Excel rows to database variables.\n * Auto-generated by scanning the original Google Sheet.\n */\n\n`;
        fileContent += `export interface ExcelMapItem {\n  rowIndex: number;\n  id: string;\n  label: string;\n  description?: string;\n  hint?: string;\n  isPercentage?: boolean;\n}\n\n`;
        
        fileContent += `export const EXCEL_ROW_MAP: Record<number, ExcelMapItem> = {\n`;
        for (const f of fields) {
            fileContent += `  ${f.rowIndex}: {\n`;
            fileContent += `    rowIndex: ${f.rowIndex},\n`;
            fileContent += `    id: "${f.id}",\n`;
            fileContent += `    label: ${JSON.stringify(f.label)},\n`;
            if (f.description) fileContent += `    description: ${JSON.stringify(f.description)},\n`;
            if (f.hint) fileContent += `    hint: ${JSON.stringify(f.hint)},\n`;
            fileContent += `  },\n`;
        }
        fileContent += `};\n\n`;

        fileContent += `export function getRowDefinition(rowIndex: number): ExcelMapItem | null {\n`;
        fileContent += `  return EXCEL_ROW_MAP[rowIndex] || null;\n`;
        fileContent += `}\n`;

        const outputPath = path.join(process.cwd(), "lib", "excel-map.ts");
        fs.writeFileSync(outputPath, fileContent);
        console.log(`Successfully generated lib/excel-map.ts with ${fields.length} mappings.`);
    }
  } catch (err) {
    console.error("Failed to fetch from sheets:", err.message);
  }
}

main();
